import { and, eq, isNotNull, lt } from 'drizzle-orm';
import type { Db } from './client.js';
import { linkCodes, webSessions } from './schema.js';

/**
 * The web "Log in with Telegram" store (ADR-0040). A free, SMS-less pairing:
 * the web creates a pending session + a short-lived link code; the Telegram bot
 * claims the code (proving the visitor controls that Telegram account); the next
 * web poll promotes the claim onto the session. Once linked, `chatId` identifies
 * the user — the same key `chat_preferences` uses — so web and bot share prefs.
 */

/** A web session: `chatId` is null while pending, set once a Telegram chat links it. */
export interface WebSession {
  readonly token: string;
  readonly chatId: number | null;
  readonly name: string | null;
}

/** Outcome of a bot-side code claim. */
export type ClaimResult = 'linked' | 'expired' | 'unknown';

/** Everything needed to open a pending pairing (ids are generated by the caller). */
export interface PendingInput {
  readonly token: string;
  readonly code: string;
  readonly now: number;
  /** How long the (eventually linked) session stays valid. */
  readonly sessionTtlMs: number;
  /** How long the visitor has to complete the pairing in Telegram. */
  readonly codeTtlMs: number;
}

export interface WebAuthRepo {
  /** Open a pending session and its short-lived link code. */
  createPending(input: PendingInput): Promise<void>;
  /**
   * Claim a code for a Telegram chat (the bot side). Idempotent: re-claiming an
   * already-claimed code by the same chat still reports `linked`.
   */
  claim(code: string, chatId: number, name: string | null, now: number): Promise<ClaimResult>;
  /**
   * Resolve a session by token, promoting a claimed code onto it. Returns the
   * session (with `chatId` set once linked, null while still pending), or null
   * when the token is unknown or the session has expired.
   */
  resolve(token: string, now: number): Promise<WebSession | null>;
  /** Sign out: drop the session and any pending code it owns. */
  logout(token: string): Promise<void>;
  /**
   * Delete expired sessions and link codes (ADR-0040 hardening). Called
   * periodically so stale, unusable rows never accumulate. Returns rows removed.
   */
  pruneExpired(now: number): Promise<number>;
}

export class DrizzleWebAuthRepo implements WebAuthRepo {
  constructor(private readonly db: Db) {}

  async createPending(input: PendingInput): Promise<void> {
    await this.db.insert(webSessions).values({
      token: input.token,
      chatId: null,
      name: null,
      createdAt: input.now,
      expiresAt: input.now + input.sessionTtlMs,
    });
    await this.db.insert(linkCodes).values({
      code: input.code,
      token: input.token,
      chatId: null,
      name: null,
      createdAt: input.now,
      expiresAt: input.now + input.codeTtlMs,
    });
  }

  async claim(code: string, chatId: number, name: string | null, now: number): Promise<ClaimResult> {
    const rows = await this.db.select().from(linkCodes).where(eq(linkCodes.code, code));
    const row = rows[0];
    if (!row) return 'unknown';
    if (row.expiresAt <= now) {
      await this.db.delete(linkCodes).where(eq(linkCodes.code, code));
      return 'expired';
    }
    // Single-claim: once a code is bound to a chat, only that chat can (re-)claim
    // it. A second chat claiming the same in-flight code must not be able to
    // hijack the pending web session by overwriting its chatId (ADR-0047).
    // Idempotent for the original claimant.
    if (row.chatId !== null && row.chatId !== chatId) return 'unknown';
    await this.db
      .update(linkCodes)
      .set({ chatId, name })
      .where(eq(linkCodes.code, code));
    return 'linked';
  }

  async resolve(token: string, now: number): Promise<WebSession | null> {
    const rows = await this.db.select().from(webSessions).where(eq(webSessions.token, token));
    const s = rows[0];
    if (!s) return null;
    if (s.expiresAt <= now) {
      await this.logout(token);
      return null;
    }
    if (s.chatId !== null) return { token: s.token, chatId: s.chatId, name: s.name };

    // Still pending: promote a claimed code onto the session, if one exists.
    const claimed = await this.db
      .select()
      .from(linkCodes)
      .where(and(eq(linkCodes.token, token), isNotNull(linkCodes.chatId)));
    const c = claimed[0];
    if (!c || c.chatId === null) return { token: s.token, chatId: null, name: null };

    await this.db
      .update(webSessions)
      .set({ chatId: c.chatId, name: c.name })
      .where(eq(webSessions.token, token));
    await this.db.delete(linkCodes).where(eq(linkCodes.token, token));
    return { token: s.token, chatId: c.chatId, name: c.name };
  }

  async logout(token: string): Promise<void> {
    await this.db.delete(linkCodes).where(eq(linkCodes.token, token));
    await this.db.delete(webSessions).where(eq(webSessions.token, token));
  }

  async pruneExpired(now: number): Promise<number> {
    const staleSessions = await this.db
      .select({ token: webSessions.token })
      .from(webSessions)
      .where(lt(webSessions.expiresAt, now));
    const staleCodes = await this.db
      .select({ code: linkCodes.code })
      .from(linkCodes)
      .where(lt(linkCodes.expiresAt, now));

    if (staleSessions.length > 0) {
      await this.db.delete(webSessions).where(lt(webSessions.expiresAt, now));
    }
    if (staleCodes.length > 0) {
      await this.db.delete(linkCodes).where(lt(linkCodes.expiresAt, now));
    }
    return staleSessions.length + staleCodes.length;
  }
}
